version: "3.8"

services:

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - webapi
    depends_on:
      - db
    command: sh -c "alembic upgrade head && python3 main.py"

  db:
    image:  postgres:17-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: post
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - webapi
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    restart: always


networks:
  webapi:
    driver: bridge