"""empty message

Revision ID: 795ea7c2fb0e
Revises: 8518043188ad
Create Date: 2024-12-16 15:59:21.758145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795ea7c2fb0e'
down_revision: Union[str, None] = '8518043188ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_chat_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_comments_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'chat', ['comments'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_comments_fkey', 'post', 'chat', ['comments'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_chat_id_fkey', 'comment', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###
